name: Error-Detection-at-Scale
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - gensim
  - pandas
  - scikit-learn
  - pyspark >=3.3.0
  - nltk
  - numpy
  - pip
  - black
  - openjdk
  - pip:
    - raha==1.25
    - git+https://github.com/okfn/messytables.git@master
